image: java:8-jdk

services:
  - mysql:latest

variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE: terraform_test_db
  MYSQL_ROOT_PASSWORD: password
  S3_BUCKET_NAME: "springboot-s3-example"

stages:
  - build
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

test:
  stage: test
  script:
    - ./gradlew check

deploy:
  image: python:latest
  script:
  - pip install awscli
  - aws s3 cp build/libs s3://$S3_BUCKET_NAME/ --exclude "*" --include "*.jar"

after_script:
  - echo "End CI"