version: "3"
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    command: [--character-set-server=utf8, --collation-server=utf8_general_ci]
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=terraform_test_db
      - MYSQL_USER=terraform
      - MYSQL_PASSWORD=password